parameters:
#    faculty_info_first_party_data.example.class: FacultyInfo\FirstPartyDataBundle\Example

services:
#    faculty_info_first_party_data.example:
#        class: %faculty_info_first_party_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
