AIESEC\Portal\DataBundle\Entity\EP:
   getters:
      durationValid:
         - NotEqualTo:
            value: 1
            message: ep.error.maxDurationLessMin
         - NotEqualTo:
            value: 2
            message: ep.error.maxDurationInvalid
         - NotEqualTo:
            value: 3
            message: ep.error.minDurationInvalid
         
   properties:
      AGBFile:
         - File:
            maxSize: 2M
            mimeTypes: [application/pdf, application/x-pdf]
            groups: [contracts]
      ANFile:
         - File:
            maxSize: 2M
            mimeTypes: [application/pdf, application/x-pdf]
            groups: [contracts]
      certificateOfEnrollment:
         - File:
            maxSize: 2M
            mimeTypes: [application/pdf, application/x-pdf]
            groups: [contracts]

      experienceReportFile:
         - NotBlank:
            groups: [report]
         - File:
            maxSize: 2M
            mimeTypes: [application/pdf, application/x-pdf]
            groups: [report]

      #although this appears to be the cleanest implementation of the validation,
      #the following is sadly ignored
      #promotionalPictures:
      #   - All:
      #      - NotBlank:
      #         groups: [report]
      #      - File:
      #         maxSize: 2M
      #         mimeTypes: [application/pdf, application/x-pdf]
      #         groups: [report]

   #private $GIPGCDP;
      earliestStartDate:
         - Date: ~
         - NotBlank: ~
      latestEndDate:
         - Date: ~
         - NotBlank: ~
         
      #duration validation handled by isser
      #minimumDuration:
      #   - Choice: {callback: getMinimumDurationArray}
      #maximumDuration:
      #   - Range:
      #      min: 6
      #      max: 78
   
      #AGBLanguage;
      #AGBVersion;
      #isAGBUploaded;
      #dateAGBSigned;
      #AGBStatus;
   
      #signedStudentContract;
      #isANUploaded;
      #dateANUploaded;
   
      #isEnrollmentCertificateUploaded;
      #dateEnrollmentCertificateUploaded;   
