parameters:
   aiesec_portal_data_service.class: AIESEC\Portal\DataBundle\Service\DataService
   aiesec_portal_timeslot_service.class: AIESEC\Portal\DataBundle\Service\TimeslotService
   aiesec_portal_membership_service.class: AIESEC\Portal\DataBundle\Service\MembershipService
   aiesec_portal_job_service.class: AIESEC\Portal\DataBundle\Service\JobService
   aiesec_portal_opportunity_service.class: AIESEC\Portal\DataBundle\Service\OpportunityService
   aiesec_portal_goal_service.class: AIESEC\Portal\DataBundle\Service\GoalService

services:
    aiesec_portal_data_service:
        class: "%aiesec_portal_data_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]

    aiesec_portal_opportunity_service:
        class: "%aiesec_portal_opportunity_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]

    aiesec_portal_timeslot_service:
        class: "%aiesec_portal_timeslot_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]

    aiesec_portal_membership_service:
        class: "%aiesec_portal_membership_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]

    aiesec_portal_job_service:
        class: "%aiesec_portal_job_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]

    aiesec_portal_goal_service:
        class: "%aiesec_portal_goal_service.class%"
        arguments: ["@logger"]
        tags:
          - { name: monolog.logger, channel: salesforce}
        calls:
          - [ setContainer,[ @service_container ] ]


