AIESEC\Portal\DataBundle\Entity\Account:
   properties:
      # only used in EP Payment
      iban:
         - NotBlank: {groups: [bankData]}
         - Iban: {groups: [bankData]}
      bic:
         - NotBlank: {groups: [bankData]}
      bankAccountOwner:
         - NotBlank: {groups: [bankData]}
      bankName:
         - NotBlank: {groups: [bankData]}
         
      # used by ProfileType
      firstName:
         - NotBlank: ~
      lastName:
         - NotBlank: ~
      gender:
         - NotBlank: ~
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getGenders]
      email:
         - NotBlank: ~
         - Email: ~
      phone:
         - NotBlank: ~
         - Length: {max: 30}
      birthDate:
         - NotBlank: ~
         - Date: ~
      university:
         - NotBlank: ~
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getUniversities]
      areaOfStudies:
         - NotBlank: ~
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getAreasOfStudies]
      semester:
         - NotBlank: ~
         - Range: {max: 99}
      graduationYear:
         - NotBlank: ~
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getGraduationYears]
      isStudent:
         - NotBlank: ~
      degreeType:
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getDegreeTypes]
      address:
         - NotBlank: ~
      zip:
         - Length: {min: 5, max: 5}
      city:
         - NotBlank: ~
      languageLevelExcellent:
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getLanguages]
            multiple: true
      languageLevelGood:
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getLanguages]
            multiple: true
      languageLevelNative:
         - Choice:
            callback: [AIESEC\Portal\DataBundle\Service\DBValues,getLanguages]
            multiple: true
      cv:
         - File:
            maxSize: 5M
            mimeTypes: [application/pdf, application/x-pdf]
      cvDateUploaded:
         - Date: ~
#    private $CV_Uploaded__c;
# 
#    private $ICC__c;
#    private $ICC_necessary__c; #is readonly
#    private $Password__c;
#    private $isPortalPasswordResetNeeded__c;
