parameters:
   facultyinfo_user_user_provider.class: FacultyInfo\UserBundle\Service\UserProvider
   facultyinfo_user_custom_encoder.class: FacultyInfo\UserBundle\Service\CustomEncoder

services:
    facultyinfo_user_user_provider:
        class: "%facultyinfo_user_user_provider.class%"
        calls:
          - [ setContainer,[ @service_container ] ]
    facultyinfo_user_custom_encoder:
        class: "%facultyinfo_user_custom_encoder.class%"