facultyinfo_dashboard:
    resource: "@FacultyInfoDashboardBundle/Resources/config/routing.yml"
    prefix:   /

facultyinfo_user:
    resource: "@FacultyInfoUserBundle/Resources/config/routing.yml"
    prefix:   /user

facultyinfo_firstparty:
    resource: "@FacultyInfoFirstPartyDataBundle/Resources/config/routing.yml"
    prefix:   /firstparty

facultyinfo_thirdparty:
    resource: "@FacultyInfoThirdPartyDataBundle/Resources/config/routing.yml"
    prefix:   /thirdparty
    
login:
    pattern:   /login
    defaults:  { _controller: FacultyInfoUserBundle:Login:login }
    
login_check:
    path:   /login_check
    
logout:
    pattern:   /logout