facultyinfo_user_overview:
    pattern:  /
    defaults: { _controller: FacultyInfoUserBundle:Overview:index }

facultyinfo_user_delete:
    pattern: /delete/{userId}/{confirmed}
    defaults: { _controller: FacultyInfoUserBundle:Overview:delete }

facultyinfo_user_update:
    pattern: /update/{userId}
    defaults: { _controller: FacultyInfoUserBundle:Update:index }
    
facultyinfo_user_create:
    pattern: /create
    defaults: { _controller: FacultyInfoUserBundle:Create:index }
    
facultyinfo_user_reset:
    pattern: /reset/{userId}/{confirmed}
    defaults: { _controller: FacultyInfoUserBundle:Overview:reset }