parameters:
#    faculty_info_user.example.class: FacultyInfo\UserBundle\Example

services:
#    faculty_info_user.example:
#        class: %faculty_info_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
