FacultyInfo\FirstPartyDataBundle\Entity\BusinesshoursFacility:
  type: entity
  table: businesshoursfacilities
  id:
    id:
      type: string
      length: 40
      
  fields:
    name:
      type: string
      length: 1000
    type:
      type: integer
    timestamp:
      type: datetime
      
  oneToMany:
    businesshours:
      targetEntity: Businesshours
      mappedBy: facility
      cascade: ["remove", "persist"]