FacultyInfo\UserBundle\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: string
      length: 40
      
  fields:
    name:
      type: string
      length: 1000
    email:
      type: string
      length: 1000
    password:
      type: string
      length: 1000