facultyinfo_firstparty_overview:
    pattern:  /
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Overview:index }
    
facultyinfo_firstparty_mapmarker_overview:
    pattern:  /mapmarker
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:overview }
    
facultyinfo_firstparty_mapmarker_category_create:
    pattern:  /mapmarker/category/create
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:createSuper }
    
facultyinfo_firstparty_mapmarker_category_create_sub:
    pattern:  /mapmarker/category/create/{superCategoryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:createSub }
    
facultyinfo_firstparty_mapmarker_category_delete:
    pattern:  /mapmarker/category/delete/{categoryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:delete }
    
facultyinfo_firstparty_mapmarker_category_update:
    pattern:  /mapmarker/category/update/{categoryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:update }
    
facultyinfo_firstparty_mapmarker_category:
    pattern:  /mapmarker/category/{categoryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerCategory:details }
    
facultyinfo_firstparty_mapmarker_entry_create:
    pattern:  /mapmarker/entry/create/{categoryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerEntry:create }
    
facultyinfo_firstparty_mapmarker_entry_delete:
    pattern:  /mapmarker/entry/delete/{entryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerEntry:delete }
    
facultyinfo_firstparty_mapmarker_entry:
    pattern:  /mapmarker/entry/{entryId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:MapmarkerEntry:update }

facultyinfo_firstparty_contact_overview:
    pattern:  /contact
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactGroup:overview }
    
facultyinfo_firstparty_contact_group_create:
    pattern:  /contact/group/create
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactGroup:create }  
  
facultyinfo_firstparty_contact_group_delete:
    pattern:  /contact/group/delete/{groupId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactGroup:delete }
    
facultyinfo_firstparty_contact_group_update:
    pattern:  /contact/group/{groupId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactGroup:update }
    
facultyinfo_firstparty_contact_person_create:
    pattern:  /contact/person/create/{groupId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactPerson:create }
    
facultyinfo_firstparty_contact_person_delete:
    pattern:  /contact/person/delete/{personId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactPerson:delete }

facultyinfo_firstparty_contact_person_update:
    pattern:  /contact/person/{personId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:ContactPerson:update }
    
facultyinfo_firstparty_businesshours_overview:
    pattern:  /businesshours
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Businesshours:overview }
    
facultyinfo_firstparty_businesshours_delete:
    pattern:  /businesshours/delete/{facilityId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Businesshours:delete }
    
facultyinfo_firstparty_businesshours_create_library:
    pattern:  /businesshours/create/library
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Businesshours:createLibrary }
    
facultyinfo_firstparty_businesshours_create_cafeteria:
    pattern:  /businesshours/create/cafeteria
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Businesshours:createCafeteria }
    
facultyinfo_firstparty_businesshours_update:
    pattern:  /businesshours/{facilityId}
    defaults: { _controller: FacultyInfoFirstPartyDataBundle:Businesshours:update }