FacultyInfo\FirstPartyDataBundle\Entity\ContactGroup:
  type: entity
  table: contactgroups
  id:
    id:
      type: string
      length: 40
      
  fields:
    title:
      type: string
      length: 1000
    description:
      type: string
      length: 5000
    timestamp:
      type: datetime
      
  oneToMany:
    persons:
      targetEntity: ContactPerson
      mappedBy: group
      cascade: ["remove"]